# Generated by Django 4.2.4 on 2023-08-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_ingredientsinrecipe_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measurement_unit',
            new_name='amount',
        ),
    ]
