# Generated by Django 4.2.4 on 2023-08-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_rename_measurement_unit_ingredient_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='amount',
            new_name='measurement_unit',
        ),
    ]
